services:
  - docker:dind

image: ruby:2.5.7
stages:
  - deploy


deploy_job:
  stage: deploy
  image: alpine:3.7
  script:
    - echo ${KUBECONFIG}
    - cat ${KUBECONFIG}
    - cat ${KUBECONFIG} > $HOME/.kube/config
  only:
    - k8


