services:
  - docker:dind

image: ruby:2.5.7
stages:
  - deploy


deploy_job:
  stage: deploy
  image: alpine:3.7
  script:
    - apk update  && apk add --no-cache curl grep
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p ${HOME}/.kube
    - cat k8s/k8s-1-17-5-do-0-sfo2-nicopaez-kubeconfig.yaml > $HOME/.kube/config
    - kubectl version
  only:
    - k8


