services:
  - docker:dind

image: ruby:2.5.7
stages:
  - build
  - package

build_job:
  stage: build
  script:
    - bundle install
    - bundle exec rake
    
package_job:
  stage: package
  image: docker:latest
  script:
    - VERSION=`cat app.rb | grep VERSION= | cut -c  10-14`
    - echo $VERSION
    - docker build -t "nicopaez/advisor:$VERSION" .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" docker.io
    - docker push "nicopaez/advisor:$VERSION"
  only:
    - setup


